<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Appdiv.Payment.AwashBank\Appdiv.Payment.AwashBank.csproj" />
    <ProjectReference Include="..\..\DirectPay.Application.Abstractions\DirectPay.Application.Abstractions.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>