<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Appdiv.Payment.CBEBirr\Appdiv.Payment.CBEBirr.csproj" />
    <ProjectReference Include="..\..\DirectPay.Application.Abstractions\DirectPay.Application.Abstractions.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.5.1" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>..\..\DirectPay.UI\bin\$(Configuration)\$(TargetFramework)\Plugins\DirectPay.Cbebirr</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>